plugins {
    id 'java'
    id 'org.springframework.boot' version '4.1.1' apply false //Download the Spring Boot plugin, but do NOT apply it to this project.
    id 'io.spring.dependency-management' version '1.1.7'
}

ext.springdocVersion = '3.1.1'

subprojects{//will be applied to all subprojects
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'checkstyle'

    group = 'de.office.dashboard'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    checkstyle {
        toolVersion = '10.26.1'
        configFile = rootProject.file('PE2CheckStyle.xml')  // <-- rootProject.file() verwenden!
    }
    tasks.withType(Checkstyle) {
        reports {
            xml.required = true
            html.required = true
        }
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES // keeps the spring framework versions up to date
        }
        dependencies {
            // springdoc-Version zentral fuer alle Module festlegen
            dependency "org.springdoc:springdoc-openapi-starter-webmvc-ui:${rootProject.ext.springdocVersion}"
        }
    }

    dependencies {
        // Shared test dependencies across all subprojects
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
        testImplementation 'org.springframework.boot:spring-boot-resttestclient'
        testImplementation 'org.springframework.boot:spring-boot-starter-restclient'
        testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
        testRuntimeOnly 'com.h2database:h2'
        testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    }

    tasks.withType(Test) {
        useJUnitPlatform()

        testLogging {
            events "passed", "skipped", "failed"
            exceptionFormat = "full"
            showExceptions = true
            showCauses = true
            showStackTraces = true
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
    }
}

description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

allprojects {
    repositories {
        mavenCentral()
    }
}


