plugins {
    id 'java'
    id 'org.springframework.boot' version '3.5.7' apply false //Download the Spring Boot plugin, but do NOT apply it to this project.
    id 'io.spring.dependency-management' version '1.1.7'
}

subprojects{//will be applied to all subprojects
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'checkstyle'

    group = 'de.itestra.dashboard'
    version = '0.0.1-SNAPSHOT'

    repositories {
        mavenCentral()
    }

    checkstyle {
        toolVersion = '10.12.5'
        configFile = rootProject.file('PE2CheckStyle.xml')  // <-- rootProject.file() verwenden!
    }
    tasks.withType(Checkstyle) {
        reports {
            xml.required = true
            html.required = true
        }
    }

    dependencyManagement {
        imports {
            mavenBom org.springframework.boot.gradle.plugin.SpringBootPlugin.BOM_COORDINATES // keeps the spring framework versions up to date
        }
    }

    dependencies {
        implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
        //developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
        runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
        testImplementation 'org.springframework.boot:spring-boot-starter-test'
        testImplementation 'org.springframework.restdocs:spring-restdocs-mockmvc'
        testRuntimeOnly 'com.h2database:h2'
        implementation 'org.liquibase:liquibase-core:4.24.0'
        implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14' // for the swagger-ui
        //runtimeOnly 'org.springframework.boot:spring-boot-devtools'
    }

    tasks.withType(Test) {
        useJUnitPlatform()

        testLogging {
            events "passed", "skipped", "failed"
            exceptionFormat = "full"
            showExceptions = true
            showCauses = true
            showStackTraces = true
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.compilerArgs.add("-parameters")
    }
}

description = 'backend'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

allprojects {
    repositories {
        mavenCentral()
        maven {
            url = "https://nexus.mekomsolutions.net/repository/maven-releases/"
        }
    }
}

ext {
    set('snippetsDir', file("build/generated-snippets"))
}

tasks.named('test') {
    outputs.dir snippetsDir
    useJUnitPlatform()
}
