spring.application.name=backend
server.port=${ITESTRA_DASHBOARD_PORT:8080}

# MariaDB Datasource
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:test}
spring.datasource.username=${DB_USER:myuser}
spring.datasource.password=${DB_PASS:secret}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

# Odoo
odoo.api.url=https://odoo15studentproject.dev.itestra.com
odoo.api.db=itestraodoo
odoo.api.username=admin
odoo.api.password=REDACTED-SECRET
odoo.api.work-location=Stuttgart

# Mattermost
mattermost.api.url=https://mattermost.itestra.com/api/v4
mattermost.api.token=REDACTED-SECRET
mattermost.api.channelId=8up7f3fykifujja7zcj6tmi9oh

# Event Notifications
# Enable or disable scheduled event reminder notifications
notifications.events.enabled=true
# Cron expression for notification schedule (default: daily at 12:00 noon)
# Format: second minute hour day-of-month month day-of-week
notifications.events.schedule.cron=0 0 12 * * *

# Cron expression for events cache refresh schedule (default: every hour at minute 12)
events.cache.refresh.schedule.cron=0 12 * * * *

# Cron expression for schedule of deleting parking entries from yesterday (default: daily at 00:00)
past.parking.entries.remove.cron=0 0 0 * * *

# Variables for module-parking
maximumParkingSpots=5
numberOfWorkingDays=10

