dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    implementation 'org.springframework.boot:spring-boot-starter-liquibase'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui'

    testImplementation project(':backend')
}

test {
    useJUnitPlatform()
}

jar {
    enabled = true
}