dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation project(':backend')
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}

test {
    useJUnitPlatform()
}

jar {
    enabled = true
}