dependencies {
    implementation project(':common')
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    runtimeOnly 'org.mariadb.jdbc:mariadb-java-client'
    implementation 'org.liquibase:liquibase-core'
    implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'


    testImplementation project(':backend')
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.12.2'
}
test {
    useJUnitPlatform()
}

jar {
    enabled = true
}
